### ISSUE TITLE
Grant and authorise hang if body parser already defined.

### ISSUE THREAD

**Issue by Volox** [thomseddon/koa-oauth-server#16]
Hi,
i noticed that the request hangs if the app have a previously defined body parser.
```js
app.use( betterBody );
app.post( '/oauth/token', oauth.grant() ); // hangs here
```

but switching the position make my app work:
```js
app.post( '/oauth/token', oauth.grant() );
app.use( betterBody );
```

**Comment by ruimarinho** [comment]
This should be fixed on the just committed 1.0.0 release via https://github.com/thomseddon/koa-oauth-server/pull/25. Allowing myself to close this but please re-open if the problem persists.
