### ISSUE TITLE
Still alive ?

### ISSUE THREAD

**Issue by antoinegomez** [thomseddon/koa-oauth-server#36]
Hello,

Project looks great but I see that the version here in github is not published on npm, last one is 1.01 which is not working: oauth2-server included does not like generators.

**Comment by ruimarinho** [comment]
@antoinegomez the project is still alive for sure. The latest version on master needs some more work to track the changes of `oauth2-server@next`, as well as some cleanup from previous versions. Expect some updates in the next few weeks while we prepare the new `oauthjs` home :)
