### ISSUE TITLE
KoaOAuthServer.prototype.authenticate lack of response

### ISSUE THREAD

**Issue by guojinlong** [thomseddon/koa-oauth-server#39]
KoaOAuthServer.prototype.authenticate = function() {
  var server = this.server;

  return function *(next) {
    var request = new Request(this.request);
    var response = new Response(this.response);

```
try {
  this.state.oauth = {
    token: yield server.authenticate(request,response)
  };
} catch (e) {
  return handleError.call(this, e);
}

yield* next;
```

  };
};

**Comment by thibremy** [comment]
Hi

@guojinlong 
I already do a PR (#35), you can use it if you want

**Comment by guojinlong** [comment]
Thank you.

**Comment by guojinlong** [comment]
Thank you. I close this issue?

**Comment by thibremy** [comment]
It's can be useful to other people to see this issue.
After all this PR is not merged yet.
